services:
  audio-dashboard:
    build: ./
    env_file: .env
    ports:
      - ${STREAMLIT_SERVER_PORT}:${STREAMLIT_SERVER_PORT}
    volumes:
      - ./app/:/app
      - ./uploads:/uploads
      - ./data:/data
    networks:
      - proxy
    environment:  
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT}
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audio-dashboard.entrypoints=https"
      - "traefik.http.routers.audio-dashboard.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.audio-dashboard.tls=true"
      - "traefik.http.routers.audio-dashboard.tls.certresolver=http"
      - "traefik.http.routers.audio-dashboard.middlewares=default@file"
      - "traefik.http.routers.audio-dashboard.service=audio-dashboard"
      - "traefik.http.services.audio-dashboard.loadbalancer.server.port=${STREAMLIT_SERVER_PORT}"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    name: proxy
    driver: bridge
    attachable: true