name: audio_dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit>=1.32.0
    - pydantic>=2.0.0
    - python-dotenv>=1.0.0
    - pydub>=0.25.1
    - ffmpeg-python>=0.2.0
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - python-magic>=0.4.27
    - python-magic-bin>=0.4.14; platform_system=="Windows"
    - libmagic; platform_system!="Windows"
    - ffmpeg
    - numpy>=1.24.0
    - scipy>=1.10.0
    - soundfile>=0.12.1
    - librosa>=0.10.0
    - matplotlib>=3.7.0
